services:
  - type: web
    name: pharmacare-api
    env: node
    plan: free
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm rebuild sqlite3
    startCommand: npm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: pharmacare-super-secure-jwt-secret-2024
      - key: CORS_ORIGIN
        value: https://pharmacare-system.surge.sh